### PR TITLE
WIP: Edit content

### PR DESCRIPTION
**Pull request by kaos**
Hi Evan,

I'm hacking on edit support. It's still work in progress so not ready for merge yet, but it's open for feedback.. :)

It's a bit cumbersome to edit text, for instance, but I like the idea that the edit field adapts to the kind of cursor you have.. ;)

Added ctrl-k support to kill input text. Got rid of extra functions in string util that wasn't needed (the rune handling).

Let me know what you think of it :)

Cheers

### CODE REVIEW

**Comment by evanmiller** [comment]
Looking like a neat and welcome addition. The `rune[]` change looks obvious in retrospect :-D.

Would you mind splitting the PR into "Refactor + Field editor improvements" and "Support for editing files"? That way we can merge the first one fairly quickly and have a longer discussion about the second.

**Comment by kaos** [comment]
Yeah, good idea. I realized that I got several things mixed up, in order for getting to state where I could continue with the editing stuff.

Will submit separate PR's for each logical change. :)

**Comment by kaos** [comment]
rebased the edit-content stuff onto #9. It's much cleaner and easier to see what is related to the editing features now :)

**Comment by evanmiller** [comment]
Great, thanks, I'll get that merged in and then we can discuss the editing UI.

**Comment by kaos** [comment]
Would be great, as I've got a few ideas, not all of them trivial to implement..

**Comment by evanmiller** [comment]
Just for the record I haven't given the editing UI too much thought. I imagined something like:
- Choose cursor style
- Press some key combination
- Field editor appears in place of cursor
- Enter value and press Return

There are some open questions here like how to handle the text cursor. In the spirit of Vim maybe we could have a Replace mode (activated with `R`) -- for text it lets you edit one byte at a time, advancing after each keypress until you press Escape, for others it brings open the field editor. I'm okay with supporting only replace operations to start and worrying about insert/delete later. I'm not sure how to handle bit patterns in this scheme (maybe the editor can display the bit pattern for all 16 hex characters as a kind of guide?).

One crucial feature IMO will be an undo/redo stack.

That's pretty much the extent of my thinking... would love to hear your ideas & perspective.

**Comment by kaos** [comment]
That sounds good, and pretty much in line with what I've been going for, thus far.

What I have now is, press `<enter>` to go into edit mode, where a field_editor is placed on the line under the cursor (i.e. between the hex lines, where the representation normally are). The edit mode behaves differently depending on the cursor mode when going into edit mode. For text, you get a one-byte input field, for numbers you get a field as wide as the cursor, and the data you type in are parsed as number. Updates to the data are applied "live", so you see what you get as you type it. This also gives a input validation of sorts, as I take it for a full round trip; editor -> scan -> data -> parse -> editor. That does present an issue when you want to enter floating point values, though, as when you enter a dot, it goes away, as a number ending with a dot is not a complete number. I have a few ideas to address that, like when you press dot, also insert a 0 following it (but don't move the cursor past it, so the next number you type will replace it), and something similar for `e` etc.

Typing `esc` aborts the edits, and brings back your original content.

That's what I've done, need to take a break for lunch now, will post more ideas I have, like for bit pattern, I envision the field editor on top of the hex representation, where you can edit the hex values directly, for instance, with the bit pattern below, to show what you get.. "live" as with the other edit modes.

**Comment by kaos** [comment]
There's a few rough edges to adress, and would like to be able to move the cursor in edit-mode perhaps?, and auto-advance in text edit mode would be nice.

Still completely missing is undo/redo.

Otherwise I think it's pretty close to your ideas.. only the bit pattern mode replace the cursor though (to see the bit pattern in edit mode as well), where as the other modes edit the value on the row below the cursor so you can see the hex value as you edit..

**Comment by kaos** [comment]
I have another idea, touching on the "press some key combination", and that is to have a configurable keymap, and in case the control with focus doesn't handle/understand a keystroke, it goes to the parent and so on, until it is either handled or it simply is an unbound key (but this would be another PR ;)

**Comment by kaos** [comment]
there's some field_editor and cursor fixes getting mixed up in here, again.. can rebase and put them in separate PR if the changes look ok to you, Evan. (commits with `field_editor` and `cursor` prefixes..)

**Comment by evanmiller** [comment]
All right, here is the deal. I don't have time to dig deeply into this PR, but I like what you've described. Will you be around to deal with any issues that come up with the new editing features? If so I'll get it merged in and send any fallout your way :-D

Also: Can you update the README to reflect the new editing stuff?

**Comment by kaos** [comment]
Yeah, I can do that. :)
There's a few kinks I'd like worked out before merging, though. Updating the readme is one of them. Was also thinking of if it wouldn't be nice with a flag to enable to open a file in read-only mode, just to be safe.

**Comment by evanmiller** [comment]
I think some kind of read-only lock would be a good idea. Perhaps when the first edit is made display some kind of confirmation dialog? ("Unlock file for editing? Y/n")

**Comment by kaos** [comment]
Ah, that's a nice idea. I'll see what I can implement.. :)

**Comment by kaos** [comment]
Still missing is the read-only lock stuff... otherwise I'm getting pretty pleased with how it behaves.

**Comment by evanmiller** [comment]
Good to hear. Add some kind of write lock and I'll merge :-D

**Comment by kaos** [comment]
Take it for a spin. I'm pretty happy with how it turned out.

I did imagine the dialog to only draw itself on top of the data tab screen.. but that wasn't really how things were knit together, and I need at least one hour sleep now before heading off to work :P 

It's a lot easier to show ad-hoc screens now, too, for other parts if/when needed.. ;)

Some screen dumps to get a quick glance at it..

Here's the basic view, read-only:
image

Confirm edit question:
image

I typed `Y`:
image

The other file was missing the `w` permission...
image

For good measure, this is what the edit field looks like, with invalid input:
image

Ah, removed the erring `d`...
image

Also notice, there's a little `*` next to the filename when it has been unlocked for editing..

**Comment by evanmiller** [comment]
Hi, I get stuck on the confirm edit dialog. Any ideas?

**Comment by kaos** [comment]
Shift Y
fre 19 feb. 2016 kl. 16:14 skrev Evan Miller notifications@github.com:

**Comment by evanmiller** [comment]
Thanks :-)

Liking it so far! Really nice work. I'll go ahead and merge to get the new features into people's hands.

**Comment by evanmiller** [comment]
Just FYI I tweaked the confirm-edit behavior so people don't get stuck:

https://github.com/evanmiller/hecate/commit/e220e4b9fd1ebd4a5ee5f8bcade7c600d422b1f6

**Comment by kaos** [comment]
Cool. I can definitely see the benefit of not requiring a capital Y ;) I blame it on being up coding during the wee tiny hours of the night.. :p

I had some sort of idea to not include enter as an accept key as it was enter that brought the dialog up (in case you hit enter again, sort of unintentionally). But perhaps that's just silly..

Anyhow, it's nice to get this stuff out the door, so we can focus on other stuff (or for me to fix it if there'll be any issues..:)

**Pull request merged**
